version: '2'
services:
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: liftprogress
        MYSQL__USER: appuser
        MYSQL_PASSWORD: password
      ports:
        - "3308:3306"
    app:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/liftprogress:rw
        ports:
            - "3002:3000"
        depends_on:
            - db
        links:
            - db
        environment:
          DB_USER: root
          DB_NAME: liftprogress
          DB_PASSWORD: password
          DB_HOST: db
